process:
	Create a cylinder and subtract inside
	Create a sphere polar array, create a rotated copy that is offset from original
	Subtract polar arrays from cylinder
	Copy Cylinder, enlarge to create outer sleeve
	Create blocks and boolean subtract to adjust height

inner_sleeve: 
	inner_radius: 700 mm
	outer_radius: 703.8
	height: 600 mm

inner_sleeve_seam:
	height: 600 mm
	width: 

inner_sleeve_seam_rivets:
	radius:	

outer_sleeve: 
	outer_radius: 707.6 mm
	inner_radius: 703.8 mm
	height: 300 mm
	y_position: 

outer_sleeve_cutting_box:
	z_bottom: 228.6 mm
	width: 1600 mm
	length: 1600 mm
	x: -800 mm
	y: -800 mm
	z_top: 533.4	

outer_sleeve_gap:

locking_bars:
	height: 300 mm
	width:
	thickness:

hole:
	radius: 50.8
	series1: 330.2 mm up
	series2: 406.4 mm up

bolt:

wing_nut:
	
