construct-images:
	montage boardwalk_plus_supports.jpg field_mesocosm.jpg mixing_chambers_brackish.png -border 2 -bordercolor black -geometry x627+5+2 -tile 3x photos.png
	montage Chamber.jpg warehouse.jpg -border 2 -bordercolor black -geometry x627+5+2 -tile 2x chambers.png
	#montage Chamber.jpg Chamber2.jpg -border 2 -bordercolor black -geometry x627+5+2 -tile 2x chambers.png

