construct-images:
	montage chamber_upclose.jpg field_mesocosm.jpg mixing_chambers.png -border 2 -bordercolor black -geometry x627+5+2 -tile 3x photos.png
	convert ../figures/tech_diagram/tech_diagram.svg -crop 80x100%+0+0 tech_diagram.png
	#montage Chamber.jpg Chamber2.jpg -border 2 -bordercolor black -geometry x627+5+2 -tile 2x chambers.png
	#montage boardwalk_plus_supports.jpg mixing_chambers_brackish.png -border 2 -bordercolor black -geometry x627+5+2 -tile 2x photos.png
	#montage warehouse.jpg -trim field_mesocosm.jpg -border 2 -bordercolor black -geometry x600+5+2 -tile 2x chambers.png

